name: tour_guide_manager
description: "Manage your excursions"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
  image_path: "assets/logo_filled.png"
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "assets/logo_bg.png"

flutter_native_splash:
  android: true
  ios: true
  web: false

  image: assets/splash.png
  color: "#052766"

  android_12:
    image: assets/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/no_data.svg
    - assets/calendar.svg
    - assets/profile.svg
    - assets/splash.png
    - assets/avatar.svg
    - assets/empty_profile.svg
